# Generated by Django 2.2 on 2023-04-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230424_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
