# Generated by Django 2.2 on 2023-04-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230424_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productId',
        ),
        migrations.AddField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
